### ISSUE TITLE
environment - ember-error-logger is undefined

### ISSUE THREAD

**Issue by niksa88** [Gavant/ember-error-logger#2]
I am not sure does I doing something wrong but I getting that "ember-error-logger" is undefined in environment.js. 

Error: "Cannot set property "listeners" of undefined.

`    if (environment === 'development' || environment === 'production') {
        ENV['ember-error-logger'].listeners = {
            'window-listener': true,
            'ember-listener': {
                ember: true,
                transitions: true,
                actions: true,
                rsvp: true
            }
        };
    }`

**Comment by billdami** [comment]
Sorry, the docs should probably be a bit more clear on this; you'll need to make sure you add the `ember-error-logger` config object to your `ENV` object first. I.e.

```javascript
var ENV = {
  //rest of env configuration object...
  'ember-error-logger': {

  }
};

if(environment === 'development') {
  //...
}
```

Let me know if this is still giving you any problems.
